### ISSUE TITLE
run keeps getting aborted 

### ISSUE THREAD

**Issue by DebdeeptoM** [gxiaolab/scAllele#13]
The run starts but soon quits with this errror 

```
<img width="947" alt="error" src="https://github.com/gxiaolab/scAllele/assets/163294649/5d812717-8428-4414-a76c-8cab193b7ca0">

COMMAND = '/home/Debdeepto.M/miniconda3/envs/scrna/bin/scAllele -b assigned_sorted.bam -g genome_index/fasta/genome.fa -o test'

[Mon, 29 Apr 2024, 05:04:27]    0.154   Running /home/Debdeepto.M/miniconda3/envs/scrna/bin/scAllele on Full mode

[Mon, 29 Apr 2024, 05:16:48]    1.061   Processing contig chr1:3199746-4495613 Length = 1295867
multiprocessing.pool.RemoteTraceback:

"""
Traceback (most recent call last):
  File "/home/Debdeepto.M/miniconda3/envs/scrna/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/Debdeepto.M/miniconda3/envs/scrna/lib/python3.10/site-packages/scAllele/scAllele.py", line 83, in process_read_cluster_1
    VAR_LIST = gqv_utils.feature_collection(SetOfVariants, SetOfReadNames, options, SM, REFPOS)
  File "/home/Debdeepto.M/miniconda3/envs/scrna/lib/python3.10/site-packages/scAllele/gqv_utils.py", line 952, in feature_collection
    pb = stats.binom_test(AC, DP, error)
AttributeError: module 'scipy.stats' has no attribute 'binom_test'
```

**Comment by giovanniquinones** [comment]
The newer scipy has replaced the binom_test with binomtest. 
You will need to install scipy version v1.11.1
