### ISSUE TITLE
Writer ImportError: cannot import name 'Reader' from 'parser'

### ISSUE THREAD

**Issue by zezhuo** [gxiaolab/scAllele#6]
Hi @giovanniquinones,

I am quiet interested in scAllele. But I got a few errors when installing this package. I was stuck by the error below. Looking forward to your help. 

scAllele --help
Traceback (most recent call last):
  File "/home/zezhuo/.conda/envs/snp/bin/scAllele", line 5, in <module>
    from scAllele.scAllele import main
  File "/home/zezhuo/.conda/envs/snp/lib/python3.8/site-packages/scAllele/scAllele.py", line 21, in <module>
    from . import gqv_glm
  File "/home/zezhuo/.conda/envs/snp/lib/python3.8/site-packages/scAllele/gqv_glm.py", line 23, in <module>
    import vcf
  File "/home/zezhuo/.conda/envs/snp/lib/python3.8/site-packages/vcf/__init__.py", line 166, in <module>
    from parser import Reader, Writer
ImportError: cannot import name 'Reader' from 'parser' (/home/zezhuo/.conda/envs/snp/lib/python3.8/lib-dynload/parser.cpython-38-x86_64-linux-gnu.so)

By the way, I tried to install scAllele with python 3.8-3.10. Only 3.8 works for me.

Regards,
Nelson

**Comment by zezhuo** [comment]
I got below packages installed via conda. After that, I got an error from numpy.

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
velocyto 0.17.17 requires Click, which is not installed.
velocyto 0.17.17 requires cython, which is not installed.
velocyto 0.17.17 requires h5py, which is not installed.
velocyto 0.17.17 requires numba, which is not installed.
Successfully installed pandas-1.3.0 scAllele-0.0.9.2
`

`$ scAllele
Traceback (most recent call last):
  File "/home/zezhuo/.conda/envs/snp/bin/scAllele", line 5, in <module>
    from scAllele.scAllele import main
  File "/home/zezhuo/.conda/envs/snp/lib/python3.8/site-packages/scAllele/scAllele.py", line 8, in <module>
    import HTSeq
  File "/home/zezhuo/.conda/envs/snp/lib/python3.8/site-packages/HTSeq/__init__.py", line 13, in <module>
    from HTSeq._HTSeq import *
  File "src/HTSeq/_HTSeq.pyx", line 1, in init HTSeq._HTSeq
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
`

**Comment by giovanniquinones** [comment]
Please make sure you are using the latest version of PyVCF module. 
If the error persists, please provide the full command and bam file to reproduce the error
